spring.application.name=ProjectManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/ProjectManagementPlatform
spring.datasource.username=postgres
spring.datasource.password=postgre@12
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=C:/Users/Ishita Jain/Downloads/ProjectManagement/ProjectManagement/src/main/resources/db/migration/generated-schema.sql