
    create table notification (
        is_read boolean,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint,
        read_at timestamp(6) with time zone,
        sent_at timestamp(6) with time zone not null,
        sent_by_id bigint,
        task_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        notification_type varchar(255) not null check ((notification_type in ('REMINDER','TASK_ASSIGNED','COMMENT_ADDED','PROJECT_INVITATION','TASK_STATUS_CHANGED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table permissions (
        id bigint generated by default as identity,
        description varchar(255),
        display_name varchar(255) not null,
        primary key (id)
    );

    create table project_invitation (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        invited_by bigint not null,
        invited_user_id bigint not null,
        project_id bigint not null,
        responded_at timestamp(6) with time zone,
        invitation_status varchar(255) not null check ((invitation_status in ('PENDING','ACCEPTED','REJECTED','EXPIRED'))),
        member_roles varchar(255) not null check ((member_roles in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table project_members (
        id bigint generated by default as identity,
        joined_at timestamp(6) with time zone,
        project_id bigint not null,
        user_id bigint not null,
        member_role varchar(255) not null check ((member_role in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
        constraint uk_project_member unique (project_id, user_id)
    );

    create table projects (
        created_at timestamp(6) with time zone not null,
        due_date timestamp(6) with time zone,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        owner_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) default 'MEDIUM' not null check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        project_name varchar(255) not null,
        status varchar(255) default 'ACTIVE' not null check ((status in ('ACTIVE','PENDING','COMPLETED','ARCHIVED','BLOCKED'))),
        primary key (id)
    );

    create table recurring_task_rule (
        day_of_month integer,
        day_of_week integer,
        interval_value integer default 1 not null,
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        next_run_at timestamp(6) with time zone,
        start_date timestamp(6) with time zone not null,
        task_id bigint not null unique,
        frequency varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        id bigint generated by default as identity,
        permission_id bigint not null,
        role_id bigint not null,
        primary key (id)
        CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        description varchar(255),
        user_role varchar(255) not null check ((user_role in ('ADMIN','MANAGER','MEMBER'))),
        primary key (role_id)
    );

    create table task_activity (
        creation_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        task_id bigint not null,
        user_id bigint not null,
        action_type varchar(255) not null check ((action_type in ('STATUS_CHANGED','DUE_DATE_CHANGED','ASSIGNMENT_UPDATED','SUB_TASK_CREATED','TASK_CREATED','PRIORITY_CHANGED'))),
        new_value varchar(255),
        old_value varchar(255),
        primary key (id)
    );

    create table task_assignment (
        assigned_at timestamp(6) with time zone not null,
        assigned_by bigint not null,
        id bigint generated by default as identity,
        responded_at timestamp(6) with time zone,
        task_id bigint not null,
        user_id bigint not null,
        description varchar(255),
        response_note varchar(255),
        status varchar(255) check ((status in ('PENDING','ACCEPTED','REJECTED'))),
        primary key (id)
    );

    create table task_attachments (
        file_size numeric(38,0) not null,
        id bigint generated by default as identity,
        task_id bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by bigint not null,
        file_name varchar(255) not null,
        file_type varchar(255) not null check ((file_type in ('CSV','EXCEL','VIDEO','DOCS','IMAGES','OTHER'))),
        url varchar(255) not null,
        primary key (id)
    );

    create table task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_comment_id bigint,
        task_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        comment varchar(255),
        primary key (id)
    );

    create table tasks (
        is_recurring boolean not null,
        priority varchar(255) check ( (priority in('LOW','HIGH','MEDIUM','URGENT')) ),
        archived_at timestamp(6) with time zone,
        archived_by bigint,
        completion_date timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        created_by bigint,
        due_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_task_id bigint,
        project_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        status varchar(255) check ((status in ('ASSIGNED','IN_PROGRESS','COMPLETED','OVERDUE','CANCELLED','ARCHIVED','BLOCKED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table user_session (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_used timestamp(6) with time zone,
        login_time timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        ip_add varchar(255) not null,
        refresh_token varchar(255) not null unique,
        session_status varchar(255) check ((session_status in ('ACTIVE','LOGGED_OUT','EXPIRED','REVOKED'))),
        primary key (id)
    );

    create table user_token (
        is_used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        token_hash varchar(255) not null unique,
        token_type varchar(255) not null check ((token_type in ('EMAIL_VERIFICATION','PASSWORD_RESET'))),
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        is_email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_login_at timestamp(6) with time zone,
        role_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        phone_number varchar(20),
        address varchar(255),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );

    alter table if exists notification 
       add constraint FKgu7aqnk7lvxtqhhsp8ltpy7il 
       foreign key (project_id) 
       references projects;

    alter table if exists notification 
       add constraint FKplj822fox7js93jahlub1mbap 
       foreign key (sent_by_id) 
       references users;

    alter table if exists notification 
       add constraint FK4j8whmrw0ba72jtrdr1d8guwr 
       foreign key (task_id) 
       references tasks;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKecl5lrd2hnfs258uauscx743w 
       foreign key (invited_by) 
       references users;

    alter table if exists project_invitation 
       add constraint FKlj4qxtgdscr1ubtyp1mt8ty2f 
       foreign key (invited_user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKp5cv96sta99mo8au33u1ng0k6 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKdki1sp2homqsdcvqm9yrix31g 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKgul2el0qjk5lsvig3wgajwm77 
       foreign key (user_id) 
       references users;

    alter table if exists projects 
       add constraint FKmueqy6cpcwpfl8gnnag4idjt9 
       foreign key (owner_id) 
       references users;

    alter table if exists recurring_task_rule 
       add constraint FKlm46ahplwu77u52hjqltkq0lo 
       foreign key (task_id) 
       references tasks;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists task_activity 
       add constraint FKs8q6cpgcvag2p3bpsrnna74qx 
       foreign key (project_id) 
       references projects;

    alter table if exists task_activity 
       add constraint FKhgmt5v3fkggo7do977l6cpi0i 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_activity 
       add constraint FK3s0dry6sv8cmc9y0u6kna5wo8 
       foreign key (user_id) 
       references users;

    alter table if exists task_assignment 
       add constraint FKrqc8s1b7r0cxkuvlqhx4vv7rb 
       foreign key (assigned_by) 
       references users;

    alter table if exists task_assignment 
       add constraint FKtcinxxcyh0hdc2md2hh78kvw4 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_assignment 
       add constraint FKakpq2xi7gmbhnk9hpeskx2h0l 
       foreign key (user_id) 
       references users;

    alter table if exists task_attachments 
       add constraint FK4eyiisq4wyx2mfj3p9h8ppufo 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_attachments 
       add constraint FK8g8b4opj0xx4ptu66b8gxkkdo 
       foreign key (uploaded_by) 
       references users;

    alter table if exists task_comment 
       add constraint FK1lcu0hwmljc3yjkqshvgqynpc 
       foreign key (parent_comment_id) 
       references task_comment;

    alter table if exists task_comment 
       add constraint FK7kiv45on4bf6my8w8mhefy9jy 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_comment 
       add constraint FKo2c4nu60419sd7mn9qexf4cqa 
       foreign key (user_id) 
       references users;

    alter table if exists tasks 
       add constraint FKb2q92d8ri0fvbojumew2omd3 
       foreign key (archived_by) 
       references users;

    alter table if exists tasks 
       add constraint FK9dgm9t7wn4w3gh57h63g712lo 
       foreign key (created_by) 
       references users;

    alter table if exists tasks 
       add constraint FK76tiq4q248au3u79a8nkexoth 
       foreign key (parent_task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKsfhn82y57i3k9uxww1s007acc 
       foreign key (project_id) 
       references projects;

    alter table if exists user_session 
       add constraint FKlr29o11uswdgcnn8swu3q15f8 
       foreign key (user_id) 
       references users;

    alter table if exists user_token 
       add constraint FKfadr8tg4d19axmfe9fltvrmqt 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;
    create table notification (
        is_read boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint,
        read_at timestamp(6) with time zone,
        sent_at timestamp(6) with time zone not null,
        sent_by_id bigint,
        task_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        notification_type varchar(255) not null check ((notification_type in ('REMINDER','TASK_ASSIGNED','COMMENT_ADDED','PROJECT_INVITATION','TASK_STATUS_CHANGED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table permissions (
        id bigint generated by default as identity,
        description varchar(255),
        display_name varchar(255) not null,
        primary key (id)
    );

    create table project_invitation (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        invited_by bigint not null,
        invited_user_id bigint not null,
        project_id bigint not null,
        responded_at timestamp(6) with time zone,
        invitation_status varchar(255) not null check ((invitation_status in ('PENDING','ACCEPTED','REJECTED','EXPIRED'))),
        member_roles varchar(255) not null check ((member_roles in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table project_members (
        id bigint generated by default as identity,
        joined_at timestamp(6) with time zone,
        project_id bigint not null,
        user_id bigint not null,
        member_role varchar(255) not null check ((member_role in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table projects (
        created_at timestamp(6) with time zone not null,
        due_date timestamp(6) with time zone,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        owner_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) default 'MEDIUM' not null check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        project_name varchar(255) not null,
        status varchar(255) default 'ACTIVE' not null check ((status in ('ACTIVE','PENDING','COMPLETED','ARCHIVED','BLOCKED'))),
        primary key (id)
    );

    create table recurring_task_rule (
        day_of_month integer,
        day_of_week integer,
        interval_value integer default 1 not null,
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        next_run_at timestamp(6) with time zone,
        start_date timestamp(6) with time zone not null,
        task_id bigint not null unique,
        frequency varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        id bigint generated by default as identity,
        permission_id bigint not null,
        role_id bigint not null,
        primary key (id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        description varchar(255),
        user_role varchar(255) not null check ((user_role in ('ADMIN','MANAGER','MEMBER'))),
        primary key (role_id)
    );

    create table task_activity (
        creation_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        task_id bigint not null,
        user_id bigint not null,
        action_type varchar(255) not null check ((action_type in ('STATUS_CHANGED','DUE_DATE_CHANGED','ASSIGNMENT_UPDATED','SUB_TASK_CREATED','TASK_CREATED','PRIORITY_CHANGED'))),
        new_value varchar(255),
        old_value varchar(255),
        primary key (id)
    );

    create table task_assignment (
        assigned_at timestamp(6) with time zone not null,
        assigned_by bigint not null,
        id bigint generated by default as identity,
        responded_at timestamp(6) with time zone,
        task_id bigint not null,
        user_id bigint not null,
        description varchar(255),
        response_note varchar(255),
        status varchar(255) check ((status in ('PENDING','ACCEPTED','REJECTED'))),
        primary key (id)
    );

    create table task_attachments (
        file_size bigint not null,
        id bigint generated by default as identity,
        task_id bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by bigint not null,
        file_name varchar(255) not null,
        file_type varchar(255) not null check ((file_type in ('CSV','EXCEL','VIDEO','DOCS','IMAGES','OTHER'))),
        url varchar(255) not null,
        primary key (id)
    );

    create table task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_comment_id bigint,
        task_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        comment varchar(255),
        primary key (id)
    );

    create table tasks (
        is_recurring boolean not null,
        archived_at timestamp(6) with time zone,
        archived_by bigint,
        completion_date timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        created_by bigint,
        due_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_task_id bigint,
        project_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        status varchar(255) check ((status in ('ASSIGNED','IN_PROGRESS','COMPLETED','OVERDUE','CANCELLED','ARCHIVED','BLOCKED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table user_session (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_used timestamp(6) with time zone,
        login_time timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        ip_add varchar(255) not null,
        refresh_token varchar(255) not null unique,
        session_status varchar(255) check ((session_status in ('ACTIVE','LOGGED_OUT','EXPIRED','REVOKED'))),
        primary key (id)
    );

    create table user_token (
        is_used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        token_hash varchar(255) not null unique,
        token_type varchar(255) not null check ((token_type in ('EMAIL_VERIFICATION','PASSWORD_RESET'))),
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        is_email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_login_at timestamp(6) with time zone,
        role_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        phone_number varchar(20),
        address varchar(255),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists notification 
       add constraint FKgu7aqnk7lvxtqhhsp8ltpy7il 
       foreign key (project_id) 
       references projects;

    alter table if exists notification 
       add constraint FKplj822fox7js93jahlub1mbap 
       foreign key (sent_by_id) 
       references users;

    alter table if exists notification 
       add constraint FK4j8whmrw0ba72jtrdr1d8guwr 
       foreign key (task_id) 
       references tasks;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKecl5lrd2hnfs258uauscx743w 
       foreign key (invited_by) 
       references users;

    alter table if exists project_invitation 
       add constraint FKlj4qxtgdscr1ubtyp1mt8ty2f 
       foreign key (invited_user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKp5cv96sta99mo8au33u1ng0k6 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKdki1sp2homqsdcvqm9yrix31g 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKgul2el0qjk5lsvig3wgajwm77 
       foreign key (user_id) 
       references users;

    alter table if exists projects 
       add constraint FKmueqy6cpcwpfl8gnnag4idjt9 
       foreign key (owner_id) 
       references users;

    alter table if exists recurring_task_rule 
       add constraint FKlm46ahplwu77u52hjqltkq0lo 
       foreign key (task_id) 
       references tasks;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists task_activity 
       add constraint FKs8q6cpgcvag2p3bpsrnna74qx 
       foreign key (project_id) 
       references projects;

    alter table if exists task_activity 
       add constraint FKhgmt5v3fkggo7do977l6cpi0i 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_activity 
       add constraint FK3s0dry6sv8cmc9y0u6kna5wo8 
       foreign key (user_id) 
       references users;

    alter table if exists task_assignment 
       add constraint FKrqc8s1b7r0cxkuvlqhx4vv7rb 
       foreign key (assigned_by) 
       references users;

    alter table if exists task_assignment 
       add constraint FKtcinxxcyh0hdc2md2hh78kvw4 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_assignment 
       add constraint FKakpq2xi7gmbhnk9hpeskx2h0l 
       foreign key (user_id) 
       references users;

    alter table if exists task_attachments 
       add constraint FK4eyiisq4wyx2mfj3p9h8ppufo 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_attachments 
       add constraint FK8g8b4opj0xx4ptu66b8gxkkdo 
       foreign key (uploaded_by) 
       references users;

    alter table if exists task_comment 
       add constraint FK1lcu0hwmljc3yjkqshvgqynpc 
       foreign key (parent_comment_id) 
       references task_comment;

    alter table if exists task_comment 
       add constraint FK7kiv45on4bf6my8w8mhefy9jy 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_comment 
       add constraint FKo2c4nu60419sd7mn9qexf4cqa 
       foreign key (user_id) 
       references users;

    alter table if exists tasks 
       add constraint FKb2q92d8ri0fvbojumew2omd3 
       foreign key (archived_by) 
       references users;

    alter table if exists tasks 
       add constraint FK9dgm9t7wn4w3gh57h63g712lo 
       foreign key (created_by) 
       references users;

    alter table if exists tasks 
       add constraint FK76tiq4q248au3u79a8nkexoth 
       foreign key (parent_task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKsfhn82y57i3k9uxww1s007acc 
       foreign key (project_id) 
       references projects;

    alter table if exists user_session 
       add constraint FKlr29o11uswdgcnn8swu3q15f8 
       foreign key (user_id) 
       references users;

    alter table if exists user_token 
       add constraint FKfadr8tg4d19axmfe9fltvrmqt 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table notification (
        is_read boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint,
        read_at timestamp(6) with time zone,
        sent_at timestamp(6) with time zone not null,
        sent_by_id bigint,
        task_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        notification_type varchar(255) not null check ((notification_type in ('REMINDER','TASK_ASSIGNED','COMMENT_ADDED','PROJECT_INVITATION','TASK_STATUS_CHANGED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table permissions (
        id bigint generated by default as identity,
        description varchar(255),
        display_name varchar(255) not null,
        primary key (id)
    );

    create table project_invitation (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        invited_by bigint not null,
        invited_user_id bigint not null,
        project_id bigint not null,
        responded_at timestamp(6) with time zone,
        invitation_status varchar(255) not null check ((invitation_status in ('PENDING','ACCEPTED','REJECTED','EXPIRED'))),
        member_roles varchar(255) not null check ((member_roles in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table project_members (
        id bigint generated by default as identity,
        joined_at timestamp(6) with time zone,
        project_id bigint not null,
        user_id bigint not null,
        member_role varchar(255) not null check ((member_role in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table projects (
        created_at timestamp(6) with time zone not null,
        due_date timestamp(6) with time zone,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        owner_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) default 'MEDIUM' not null check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        project_name varchar(255) not null,
        status varchar(255) default 'ACTIVE' not null check ((status in ('ACTIVE','PENDING','COMPLETED','ARCHIVED','BLOCKED'))),
        primary key (id)
    );

    create table recurring_task_rule (
        day_of_month integer,
        day_of_week integer,
        interval_value integer default 1 not null,
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        next_run_at timestamp(6) with time zone,
        start_date timestamp(6) with time zone not null,
        task_id bigint not null unique,
        frequency varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        id bigint generated by default as identity,
        permission_id bigint not null,
        role_id bigint not null,
        primary key (id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        description varchar(255),
        user_role varchar(255) not null check ((user_role in ('ADMIN','MANAGER','MEMBER'))),
        primary key (role_id)
    );

    create table task_activity (
        creation_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        task_id bigint not null,
        user_id bigint not null,
        action_type varchar(255) not null check ((action_type in ('STATUS_CHANGED','DUE_DATE_CHANGED','ASSIGNMENT_UPDATED','SUB_TASK_CREATED','TASK_CREATED','PRIORITY_CHANGED'))),
        new_value varchar(255),
        old_value varchar(255),
        primary key (id)
    );

    create table task_assignment (
        assigned_at timestamp(6) with time zone not null,
        assigned_by bigint not null,
        id bigint generated by default as identity,
        responded_at timestamp(6) with time zone,
        task_id bigint not null,
        user_id bigint not null,
        description varchar(255),
        response_note varchar(255),
        status varchar(255) check ((status in ('PENDING','ACCEPTED','REJECTED'))),
        primary key (id)
    );

    create table task_attachments (
        file_size bigint not null,
        id bigint generated by default as identity,
        task_id bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by bigint not null,
        file_name varchar(255) not null,
        file_type varchar(255) not null check ((file_type in ('CSV','EXCEL','VIDEO','DOCS','IMAGES','OTHER'))),
        url varchar(255) not null,
        primary key (id)
    );

    create table task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_comment_id bigint,
        task_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        comment varchar(255),
        primary key (id)
    );

    create table tasks (
        is_recurring boolean not null,
        archived_at timestamp(6) with time zone,
        archived_by bigint,
        completion_date timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        created_by bigint,
        due_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_task_id bigint,
        project_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        status varchar(255) check ((status in ('ASSIGNED','IN_PROGRESS','COMPLETED','OVERDUE','CANCELLED','ARCHIVED','BLOCKED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table user_session (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_used timestamp(6) with time zone,
        login_time timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        ip_add varchar(255) not null,
        refresh_token varchar(255) not null unique,
        session_status varchar(255) check ((session_status in ('ACTIVE','LOGGED_OUT','EXPIRED','REVOKED'))),
        primary key (id)
    );

    create table user_token (
        is_used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        token_hash varchar(255) not null unique,
        token_type varchar(255) not null check ((token_type in ('EMAIL_VERIFICATION','PASSWORD_RESET'))),
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        is_email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_login_at timestamp(6) with time zone,
        role_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        phone_number varchar(20),
        address varchar(255),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists notification 
       add constraint FKgu7aqnk7lvxtqhhsp8ltpy7il 
       foreign key (project_id) 
       references projects;

    alter table if exists notification 
       add constraint FKplj822fox7js93jahlub1mbap 
       foreign key (sent_by_id) 
       references users;

    alter table if exists notification 
       add constraint FK4j8whmrw0ba72jtrdr1d8guwr 
       foreign key (task_id) 
       references tasks;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKecl5lrd2hnfs258uauscx743w 
       foreign key (invited_by) 
       references users;

    alter table if exists project_invitation 
       add constraint FKlj4qxtgdscr1ubtyp1mt8ty2f 
       foreign key (invited_user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKp5cv96sta99mo8au33u1ng0k6 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKdki1sp2homqsdcvqm9yrix31g 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKgul2el0qjk5lsvig3wgajwm77 
       foreign key (user_id) 
       references users;

    alter table if exists projects 
       add constraint FKmueqy6cpcwpfl8gnnag4idjt9 
       foreign key (owner_id) 
       references users;

    alter table if exists recurring_task_rule 
       add constraint FKlm46ahplwu77u52hjqltkq0lo 
       foreign key (task_id) 
       references tasks;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists task_activity 
       add constraint FKs8q6cpgcvag2p3bpsrnna74qx 
       foreign key (project_id) 
       references projects;

    alter table if exists task_activity 
       add constraint FKhgmt5v3fkggo7do977l6cpi0i 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_activity 
       add constraint FK3s0dry6sv8cmc9y0u6kna5wo8 
       foreign key (user_id) 
       references users;

    alter table if exists task_assignment 
       add constraint FKrqc8s1b7r0cxkuvlqhx4vv7rb 
       foreign key (assigned_by) 
       references users;

    alter table if exists task_assignment 
       add constraint FKtcinxxcyh0hdc2md2hh78kvw4 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_assignment 
       add constraint FKakpq2xi7gmbhnk9hpeskx2h0l 
       foreign key (user_id) 
       references users;

    alter table if exists task_attachments 
       add constraint FK4eyiisq4wyx2mfj3p9h8ppufo 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_attachments 
       add constraint FK8g8b4opj0xx4ptu66b8gxkkdo 
       foreign key (uploaded_by) 
       references users;

    alter table if exists task_comment 
       add constraint FK1lcu0hwmljc3yjkqshvgqynpc 
       foreign key (parent_comment_id) 
       references task_comment;

    alter table if exists task_comment 
       add constraint FK7kiv45on4bf6my8w8mhefy9jy 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_comment 
       add constraint FKo2c4nu60419sd7mn9qexf4cqa 
       foreign key (user_id) 
       references users;

    alter table if exists tasks 
       add constraint FKb2q92d8ri0fvbojumew2omd3 
       foreign key (archived_by) 
       references users;

    alter table if exists tasks 
       add constraint FK9dgm9t7wn4w3gh57h63g712lo 
       foreign key (created_by) 
       references users;

    alter table if exists tasks 
       add constraint FK76tiq4q248au3u79a8nkexoth 
       foreign key (parent_task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKsfhn82y57i3k9uxww1s007acc 
       foreign key (project_id) 
       references projects;

    alter table if exists user_session 
       add constraint FKlr29o11uswdgcnn8swu3q15f8 
       foreign key (user_id) 
       references users;

    alter table if exists user_token 
       add constraint FKfadr8tg4d19axmfe9fltvrmqt 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table notification (
        is_read boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint,
        read_at timestamp(6) with time zone,
        sent_at timestamp(6) with time zone not null,
        sent_by_id bigint,
        task_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        notification_type varchar(255) not null check ((notification_type in ('REMINDER','TASK_ASSIGNED','COMMENT_ADDED','PROJECT_INVITATION','TASK_STATUS_CHANGED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table permissions (
        id bigint generated by default as identity,
        description varchar(255),
        display_name varchar(255) not null,
        primary key (id)
    );

    create table project_invitation (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        invited_by bigint not null,
        invited_user_id bigint not null,
        project_id bigint not null,
        responded_at timestamp(6) with time zone,
        invitation_status varchar(255) not null check ((invitation_status in ('PENDING','ACCEPTED','REJECTED','EXPIRED'))),
        member_roles varchar(255) not null check ((member_roles in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table project_members (
        id bigint generated by default as identity,
        joined_at timestamp(6) with time zone,
        project_id bigint not null,
        user_id bigint not null,
        member_role varchar(255) not null check ((member_role in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table projects (
        created_at timestamp(6) with time zone not null,
        due_date timestamp(6) with time zone,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        owner_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) default 'MEDIUM' not null check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        project_name varchar(255) not null,
        status varchar(255) default 'ACTIVE' not null check ((status in ('ACTIVE','PENDING','COMPLETED','ARCHIVED','BLOCKED'))),
        primary key (id)
    );

    create table recurring_task_rule (
        day_of_month integer,
        day_of_week integer,
        interval_value integer default 1 not null,
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        next_run_at timestamp(6) with time zone,
        start_date timestamp(6) with time zone not null,
        task_id bigint not null unique,
        frequency varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        id bigint generated by default as identity,
        permission_id bigint not null,
        role_id bigint not null,
        primary key (id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        description varchar(255),
        user_role varchar(255) not null check ((user_role in ('ADMIN','MANAGER','MEMBER'))),
        primary key (role_id)
    );

    create table task_activity (
        creation_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        task_id bigint not null,
        user_id bigint not null,
        action_type varchar(255) not null check ((action_type in ('STATUS_CHANGED','DUE_DATE_CHANGED','ASSIGNMENT_UPDATED','SUB_TASK_CREATED','TASK_CREATED','PRIORITY_CHANGED'))),
        new_value varchar(255),
        old_value varchar(255),
        primary key (id)
    );

    create table task_assignment (
        assigned_at timestamp(6) with time zone not null,
        assigned_by bigint not null,
        id bigint generated by default as identity,
        responded_at timestamp(6) with time zone,
        task_id bigint not null,
        user_id bigint not null,
        description varchar(255),
        response_note varchar(255),
        status varchar(255) check ((status in ('PENDING','ACCEPTED','REJECTED'))),
        primary key (id)
    );

    create table task_attachments (
        file_size bigint not null,
        id bigint generated by default as identity,
        task_id bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by bigint not null,
        file_name varchar(255) not null,
        file_type varchar(255) not null check ((file_type in ('CSV','EXCEL','VIDEO','DOCS','IMAGES','OTHER'))),
        url varchar(255) not null,
        primary key (id)
    );

    create table task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_comment_id bigint,
        task_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        comment varchar(255),
        primary key (id)
    );

    create table tasks (
        is_recurring boolean not null,
        archived_at timestamp(6) with time zone,
        archived_by bigint,
        completion_date timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        created_by bigint,
        due_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_task_id bigint,
        project_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        status varchar(255) check ((status in ('ASSIGNED','IN_PROGRESS','COMPLETED','OVERDUE','CANCELLED','ARCHIVED','BLOCKED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table user_session (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_used timestamp(6) with time zone,
        login_time timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        ip_add varchar(255) not null,
        refresh_token varchar(255) not null unique,
        session_status varchar(255) check ((session_status in ('ACTIVE','LOGGED_OUT','EXPIRED','REVOKED'))),
        primary key (id)
    );

    create table user_token (
        is_used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        token_hash varchar(255) not null unique,
        token_type varchar(255) not null check ((token_type in ('EMAIL_VERIFICATION','PASSWORD_RESET'))),
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        is_email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_login_at timestamp(6) with time zone,
        role_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        phone_number varchar(20),
        address varchar(255),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists notification 
       add constraint FKgu7aqnk7lvxtqhhsp8ltpy7il 
       foreign key (project_id) 
       references projects;

    alter table if exists notification 
       add constraint FKplj822fox7js93jahlub1mbap 
       foreign key (sent_by_id) 
       references users;

    alter table if exists notification 
       add constraint FK4j8whmrw0ba72jtrdr1d8guwr 
       foreign key (task_id) 
       references tasks;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKecl5lrd2hnfs258uauscx743w 
       foreign key (invited_by) 
       references users;

    alter table if exists project_invitation 
       add constraint FKlj4qxtgdscr1ubtyp1mt8ty2f 
       foreign key (invited_user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKp5cv96sta99mo8au33u1ng0k6 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKdki1sp2homqsdcvqm9yrix31g 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKgul2el0qjk5lsvig3wgajwm77 
       foreign key (user_id) 
       references users;

    alter table if exists projects 
       add constraint FKmueqy6cpcwpfl8gnnag4idjt9 
       foreign key (owner_id) 
       references users;

    alter table if exists recurring_task_rule 
       add constraint FKlm46ahplwu77u52hjqltkq0lo 
       foreign key (task_id) 
       references tasks;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists task_activity 
       add constraint FKs8q6cpgcvag2p3bpsrnna74qx 
       foreign key (project_id) 
       references projects;

    alter table if exists task_activity 
       add constraint FKhgmt5v3fkggo7do977l6cpi0i 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_activity 
       add constraint FK3s0dry6sv8cmc9y0u6kna5wo8 
       foreign key (user_id) 
       references users;

    alter table if exists task_assignment 
       add constraint FKrqc8s1b7r0cxkuvlqhx4vv7rb 
       foreign key (assigned_by) 
       references users;

    alter table if exists task_assignment 
       add constraint FKtcinxxcyh0hdc2md2hh78kvw4 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_assignment 
       add constraint FKakpq2xi7gmbhnk9hpeskx2h0l 
       foreign key (user_id) 
       references users;

    alter table if exists task_attachments 
       add constraint FK4eyiisq4wyx2mfj3p9h8ppufo 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_attachments 
       add constraint FK8g8b4opj0xx4ptu66b8gxkkdo 
       foreign key (uploaded_by) 
       references users;

    alter table if exists task_comment 
       add constraint FK1lcu0hwmljc3yjkqshvgqynpc 
       foreign key (parent_comment_id) 
       references task_comment;

    alter table if exists task_comment 
       add constraint FK7kiv45on4bf6my8w8mhefy9jy 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_comment 
       add constraint FKo2c4nu60419sd7mn9qexf4cqa 
       foreign key (user_id) 
       references users;

    alter table if exists tasks 
       add constraint FKb2q92d8ri0fvbojumew2omd3 
       foreign key (archived_by) 
       references users;

    alter table if exists tasks 
       add constraint FK9dgm9t7wn4w3gh57h63g712lo 
       foreign key (created_by) 
       references users;

    alter table if exists tasks 
       add constraint FK76tiq4q248au3u79a8nkexoth 
       foreign key (parent_task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKsfhn82y57i3k9uxww1s007acc 
       foreign key (project_id) 
       references projects;

    alter table if exists user_session 
       add constraint FKlr29o11uswdgcnn8swu3q15f8 
       foreign key (user_id) 
       references users;

    alter table if exists user_token 
       add constraint FKfadr8tg4d19axmfe9fltvrmqt 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table notification (
        is_read boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint,
        read_at timestamp(6) with time zone,
        sent_at timestamp(6) with time zone not null,
        sent_by_id bigint,
        task_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        notification_type varchar(255) not null check ((notification_type in ('REMINDER','TASK_ASSIGNED','COMMENT_ADDED','PROJECT_INVITATION','TASK_STATUS_CHANGED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table permissions (
        id bigint generated by default as identity,
        description varchar(255),
        display_name varchar(255) not null,
        primary key (id)
    );

    create table project_invitation (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        invited_by bigint not null,
        invited_user_id bigint not null,
        project_id bigint not null,
        responded_at timestamp(6) with time zone,
        invitation_status varchar(255) not null check ((invitation_status in ('PENDING','ACCEPTED','REJECTED','EXPIRED'))),
        member_roles varchar(255) not null check ((member_roles in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table project_members (
        id bigint generated by default as identity,
        joined_at timestamp(6) with time zone,
        project_id bigint not null,
        user_id bigint not null,
        member_role varchar(255) not null check ((member_role in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table projects (
        created_at timestamp(6) with time zone not null,
        due_date timestamp(6) with time zone,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        owner_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) default 'MEDIUM' not null check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        project_name varchar(255) not null,
        status varchar(255) default 'ACTIVE' not null check ((status in ('ACTIVE','PENDING','COMPLETED','ARCHIVED','BLOCKED'))),
        primary key (id)
    );

    create table recurring_task_rule (
        day_of_month integer,
        day_of_week integer,
        interval_value integer default 1 not null,
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        next_run_at timestamp(6) with time zone,
        start_date timestamp(6) with time zone not null,
        task_id bigint not null unique,
        frequency varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        id bigint generated by default as identity,
        permission_id bigint not null,
        role_id bigint not null,
        primary key (id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        description varchar(255),
        user_role varchar(255) not null check ((user_role in ('ADMIN','MANAGER','MEMBER'))),
        primary key (role_id)
    );

    create table task_activity (
        creation_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        task_id bigint not null,
        user_id bigint not null,
        action_type varchar(255) not null check ((action_type in ('STATUS_CHANGED','DUE_DATE_CHANGED','ASSIGNMENT_UPDATED','SUB_TASK_CREATED','TASK_CREATED','PRIORITY_CHANGED'))),
        new_value varchar(255),
        old_value varchar(255),
        primary key (id)
    );

    create table task_assignment (
        assigned_at timestamp(6) with time zone not null,
        assigned_by bigint not null,
        id bigint generated by default as identity,
        responded_at timestamp(6) with time zone,
        task_id bigint not null,
        user_id bigint not null,
        description varchar(255),
        response_note varchar(255),
        status varchar(255) check ((status in ('PENDING','ACCEPTED','REJECTED'))),
        primary key (id)
    );

    create table task_attachments (
        file_size bigint not null,
        id bigint generated by default as identity,
        task_id bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by bigint not null,
        file_name varchar(255) not null,
        file_type varchar(255) not null check ((file_type in ('CSV','EXCEL','VIDEO','DOCS','IMAGES','OTHER'))),
        url varchar(255) not null,
        primary key (id)
    );

    create table task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_comment_id bigint,
        task_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        comment varchar(255),
        primary key (id)
    );

    create table tasks (
        is_recurring boolean not null,
        archived_at timestamp(6) with time zone,
        archived_by bigint,
        completion_date timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        created_by bigint,
        due_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_task_id bigint,
        project_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        status varchar(255) check ((status in ('ASSIGNED','IN_PROGRESS','COMPLETED','OVERDUE','CANCELLED','ARCHIVED','BLOCKED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table user_session (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_used timestamp(6) with time zone,
        login_time timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        ip_add varchar(255) not null,
        refresh_token varchar(255) not null unique,
        session_status varchar(255) check ((session_status in ('ACTIVE','LOGGED_OUT','EXPIRED','REVOKED'))),
        primary key (id)
    );

    create table user_token (
        is_used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        token_hash varchar(255) not null unique,
        token_type varchar(255) not null check ((token_type in ('EMAIL_VERIFICATION','PASSWORD_RESET'))),
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        is_email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_login_at timestamp(6) with time zone,
        role_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        phone_number varchar(20),
        address varchar(255),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists notification 
       add constraint FKgu7aqnk7lvxtqhhsp8ltpy7il 
       foreign key (project_id) 
       references projects;

    alter table if exists notification 
       add constraint FKplj822fox7js93jahlub1mbap 
       foreign key (sent_by_id) 
       references users;

    alter table if exists notification 
       add constraint FK4j8whmrw0ba72jtrdr1d8guwr 
       foreign key (task_id) 
       references tasks;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKecl5lrd2hnfs258uauscx743w 
       foreign key (invited_by) 
       references users;

    alter table if exists project_invitation 
       add constraint FKlj4qxtgdscr1ubtyp1mt8ty2f 
       foreign key (invited_user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKp5cv96sta99mo8au33u1ng0k6 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKdki1sp2homqsdcvqm9yrix31g 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKgul2el0qjk5lsvig3wgajwm77 
       foreign key (user_id) 
       references users;

    alter table if exists projects 
       add constraint FKmueqy6cpcwpfl8gnnag4idjt9 
       foreign key (owner_id) 
       references users;

    alter table if exists recurring_task_rule 
       add constraint FKlm46ahplwu77u52hjqltkq0lo 
       foreign key (task_id) 
       references tasks;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists task_activity 
       add constraint FKs8q6cpgcvag2p3bpsrnna74qx 
       foreign key (project_id) 
       references projects;

    alter table if exists task_activity 
       add constraint FKhgmt5v3fkggo7do977l6cpi0i 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_activity 
       add constraint FK3s0dry6sv8cmc9y0u6kna5wo8 
       foreign key (user_id) 
       references users;

    alter table if exists task_assignment 
       add constraint FKrqc8s1b7r0cxkuvlqhx4vv7rb 
       foreign key (assigned_by) 
       references users;

    alter table if exists task_assignment 
       add constraint FKtcinxxcyh0hdc2md2hh78kvw4 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_assignment 
       add constraint FKakpq2xi7gmbhnk9hpeskx2h0l 
       foreign key (user_id) 
       references users;

    alter table if exists task_attachments 
       add constraint FK4eyiisq4wyx2mfj3p9h8ppufo 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_attachments 
       add constraint FK8g8b4opj0xx4ptu66b8gxkkdo 
       foreign key (uploaded_by) 
       references users;

    alter table if exists task_comment 
       add constraint FK1lcu0hwmljc3yjkqshvgqynpc 
       foreign key (parent_comment_id) 
       references task_comment;

    alter table if exists task_comment 
       add constraint FK7kiv45on4bf6my8w8mhefy9jy 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_comment 
       add constraint FKo2c4nu60419sd7mn9qexf4cqa 
       foreign key (user_id) 
       references users;

    alter table if exists tasks 
       add constraint FKb2q92d8ri0fvbojumew2omd3 
       foreign key (archived_by) 
       references users;

    alter table if exists tasks 
       add constraint FK9dgm9t7wn4w3gh57h63g712lo 
       foreign key (created_by) 
       references users;

    alter table if exists tasks 
       add constraint FK76tiq4q248au3u79a8nkexoth 
       foreign key (parent_task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKsfhn82y57i3k9uxww1s007acc 
       foreign key (project_id) 
       references projects;

    alter table if exists user_session 
       add constraint FKlr29o11uswdgcnn8swu3q15f8 
       foreign key (user_id) 
       references users;

    alter table if exists user_token 
       add constraint FKfadr8tg4d19axmfe9fltvrmqt 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table notification (
        is_read boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint,
        read_at timestamp(6) with time zone,
        sent_at timestamp(6) with time zone not null,
        sent_by_id bigint,
        task_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        notification_type varchar(255) not null check ((notification_type in ('REMINDER','TASK_ASSIGNED','COMMENT_ADDED','PROJECT_INVITATION','TASK_STATUS_CHANGED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table permissions (
        id bigint generated by default as identity,
        description varchar(255),
        display_name varchar(255) not null,
        primary key (id)
    );

    create table project_invitation (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        invited_by bigint not null,
        invited_user_id bigint not null,
        project_id bigint not null,
        responded_at timestamp(6) with time zone,
        invitation_status varchar(255) not null check ((invitation_status in ('PENDING','ACCEPTED','REJECTED','EXPIRED'))),
        member_roles varchar(255) not null check ((member_roles in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table project_members (
        id bigint generated by default as identity,
        joined_at timestamp(6) with time zone,
        project_id bigint not null,
        user_id bigint not null,
        member_role varchar(255) not null check ((member_role in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table projects (
        created_at timestamp(6) with time zone not null,
        due_date timestamp(6) with time zone,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        owner_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) default 'MEDIUM' not null check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        project_name varchar(255) not null,
        status varchar(255) default 'ACTIVE' not null check ((status in ('ACTIVE','PENDING','COMPLETED','ARCHIVED','BLOCKED'))),
        primary key (id)
    );

    create table recurring_task_rule (
        day_of_month integer,
        day_of_week integer,
        interval_value integer default 1 not null,
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        next_run_at timestamp(6) with time zone,
        start_date timestamp(6) with time zone not null,
        task_id bigint not null unique,
        frequency varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        id bigint generated by default as identity,
        permission_id bigint not null,
        role_id bigint not null,
        primary key (id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        description varchar(255),
        user_role varchar(255) not null check ((user_role in ('ADMIN','MANAGER','MEMBER'))),
        primary key (role_id)
    );

    create table task_activity (
        creation_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        task_id bigint not null,
        user_id bigint not null,
        action_type varchar(255) not null check ((action_type in ('STATUS_CHANGED','DUE_DATE_CHANGED','ASSIGNMENT_UPDATED','SUB_TASK_CREATED','TASK_CREATED','PRIORITY_CHANGED'))),
        new_value varchar(255),
        old_value varchar(255),
        primary key (id)
    );

    create table task_assignment (
        assigned_at timestamp(6) with time zone not null,
        assigned_by bigint not null,
        id bigint generated by default as identity,
        responded_at timestamp(6) with time zone,
        task_id bigint not null,
        user_id bigint not null,
        description varchar(255),
        response_note varchar(255),
        status varchar(255) check ((status in ('PENDING','ACCEPTED','REJECTED'))),
        primary key (id)
    );

    create table task_attachments (
        file_size bigint not null,
        id bigint generated by default as identity,
        task_id bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by bigint not null,
        file_name varchar(255) not null,
        file_type varchar(255) not null check ((file_type in ('CSV','EXCEL','VIDEO','DOCS','IMAGES','OTHER'))),
        url varchar(255) not null,
        primary key (id)
    );

    create table task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_comment_id bigint,
        task_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        comment varchar(255),
        primary key (id)
    );

    create table tasks (
        is_recurring boolean not null,
        archived_at timestamp(6) with time zone,
        archived_by bigint,
        completion_date timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        created_by bigint,
        due_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_task_id bigint,
        project_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        status varchar(255) check ((status in ('ASSIGNED','IN_PROGRESS','COMPLETED','OVERDUE','CANCELLED','ARCHIVED','BLOCKED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table user_session (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_used timestamp(6) with time zone,
        login_time timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        ip_add varchar(255) not null,
        refresh_token varchar(255) not null unique,
        session_status varchar(255) check ((session_status in ('ACTIVE','LOGGED_OUT','EXPIRED','REVOKED'))),
        primary key (id)
    );

    create table user_token (
        is_used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        token_hash varchar(255) not null unique,
        token_type varchar(255) not null check ((token_type in ('EMAIL_VERIFICATION','PASSWORD_RESET'))),
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        is_email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_login_at timestamp(6) with time zone,
        role_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        phone_number varchar(20),
        address varchar(255),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists notification 
       add constraint FKgu7aqnk7lvxtqhhsp8ltpy7il 
       foreign key (project_id) 
       references projects;

    alter table if exists notification 
       add constraint FKplj822fox7js93jahlub1mbap 
       foreign key (sent_by_id) 
       references users;

    alter table if exists notification 
       add constraint FK4j8whmrw0ba72jtrdr1d8guwr 
       foreign key (task_id) 
       references tasks;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKecl5lrd2hnfs258uauscx743w 
       foreign key (invited_by) 
       references users;

    alter table if exists project_invitation 
       add constraint FKlj4qxtgdscr1ubtyp1mt8ty2f 
       foreign key (invited_user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKp5cv96sta99mo8au33u1ng0k6 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKdki1sp2homqsdcvqm9yrix31g 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKgul2el0qjk5lsvig3wgajwm77 
       foreign key (user_id) 
       references users;

    alter table if exists projects 
       add constraint FKmueqy6cpcwpfl8gnnag4idjt9 
       foreign key (owner_id) 
       references users;

    alter table if exists recurring_task_rule 
       add constraint FKlm46ahplwu77u52hjqltkq0lo 
       foreign key (task_id) 
       references tasks;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists task_activity 
       add constraint FKs8q6cpgcvag2p3bpsrnna74qx 
       foreign key (project_id) 
       references projects;

    alter table if exists task_activity 
       add constraint FKhgmt5v3fkggo7do977l6cpi0i 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_activity 
       add constraint FK3s0dry6sv8cmc9y0u6kna5wo8 
       foreign key (user_id) 
       references users;

    alter table if exists task_assignment 
       add constraint FKrqc8s1b7r0cxkuvlqhx4vv7rb 
       foreign key (assigned_by) 
       references users;

    alter table if exists task_assignment 
       add constraint FKtcinxxcyh0hdc2md2hh78kvw4 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_assignment 
       add constraint FKakpq2xi7gmbhnk9hpeskx2h0l 
       foreign key (user_id) 
       references users;

    alter table if exists task_attachments 
       add constraint FK4eyiisq4wyx2mfj3p9h8ppufo 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_attachments 
       add constraint FK8g8b4opj0xx4ptu66b8gxkkdo 
       foreign key (uploaded_by) 
       references users;

    alter table if exists task_comment 
       add constraint FK1lcu0hwmljc3yjkqshvgqynpc 
       foreign key (parent_comment_id) 
       references task_comment;

    alter table if exists task_comment 
       add constraint FK7kiv45on4bf6my8w8mhefy9jy 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_comment 
       add constraint FKo2c4nu60419sd7mn9qexf4cqa 
       foreign key (user_id) 
       references users;

    alter table if exists tasks 
       add constraint FKb2q92d8ri0fvbojumew2omd3 
       foreign key (archived_by) 
       references users;

    alter table if exists tasks 
       add constraint FK9dgm9t7wn4w3gh57h63g712lo 
       foreign key (created_by) 
       references users;

    alter table if exists tasks 
       add constraint FK76tiq4q248au3u79a8nkexoth 
       foreign key (parent_task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKsfhn82y57i3k9uxww1s007acc 
       foreign key (project_id) 
       references projects;

    alter table if exists user_session 
       add constraint FKlr29o11uswdgcnn8swu3q15f8 
       foreign key (user_id) 
       references users;

    alter table if exists user_token 
       add constraint FKfadr8tg4d19axmfe9fltvrmqt 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    create table notification (
        is_read boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint,
        read_at timestamp(6) with time zone,
        sent_at timestamp(6) with time zone not null,
        sent_by_id bigint,
        task_id bigint,
        user_id bigint not null,
        message varchar(255) not null,
        notification_type varchar(255) not null check ((notification_type in ('REMINDER','TASK_ASSIGNED','COMMENT_ADDED','PROJECT_INVITATION','TASK_STATUS_CHANGED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table permissions (
        id bigint generated by default as identity,
        description varchar(255),
        display_name varchar(255) not null,
        primary key (id)
    );

    create table project_invitation (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        invited_by bigint not null,
        invited_user_id bigint not null,
        project_id bigint not null,
        responded_at timestamp(6) with time zone,
        invitation_status varchar(255) not null check ((invitation_status in ('PENDING','ACCEPTED','REJECTED','EXPIRED'))),
        member_roles varchar(255) not null check ((member_roles in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table project_members (
        id bigint generated by default as identity,
        joined_at timestamp(6) with time zone,
        project_id bigint not null,
        user_id bigint not null,
        member_role varchar(255) not null check ((member_role in ('OWNER','EDITOR','VIEWER'))),
        primary key (id)
    );

    create table projects (
        created_at timestamp(6) with time zone not null,
        due_date timestamp(6) with time zone,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        owner_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) default 'MEDIUM' not null check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        project_name varchar(255) not null,
        status varchar(255) default 'ACTIVE' not null check ((status in ('ACTIVE','PENDING','COMPLETED','ARCHIVED','BLOCKED'))),
        primary key (id)
    );

    create table recurring_task_rule (
        day_of_month integer,
        day_of_week integer,
        interval_value integer default 1 not null,
        is_active boolean not null,
        created_at timestamp(6) with time zone not null,
        end_date timestamp(6) with time zone,
        id bigint generated by default as identity,
        next_run_at timestamp(6) with time zone,
        start_date timestamp(6) with time zone not null,
        task_id bigint not null unique,
        frequency varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        id bigint generated by default as identity,
        permission_id bigint not null,
        role_id bigint not null,
        primary key (id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        description varchar(255),
        user_role varchar(255) not null check ((user_role in ('ADMIN','MANAGER','MEMBER'))),
        primary key (role_id)
    );

    create table task_activity (
        creation_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        task_id bigint not null,
        user_id bigint not null,
        action_type varchar(255) not null check ((action_type in ('STATUS_CHANGED','DUE_DATE_CHANGED','ASSIGNMENT_UPDATED','SUB_TASK_CREATED','TASK_CREATED','PRIORITY_CHANGED'))),
        new_value varchar(255),
        old_value varchar(255),
        primary key (id)
    );

    create table task_assignment (
        assigned_at timestamp(6) with time zone not null,
        assigned_by bigint not null,
        id bigint generated by default as identity,
        responded_at timestamp(6) with time zone,
        task_id bigint not null,
        user_id bigint not null,
        description varchar(255),
        response_note varchar(255),
        status varchar(255) check ((status in ('PENDING','ACCEPTED','REJECTED'))),
        primary key (id)
    );

    create table task_attachments (
        file_size bigint not null,
        id bigint generated by default as identity,
        task_id bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by bigint not null,
        file_name varchar(255) not null,
        file_type varchar(255) not null check ((file_type in ('CSV','EXCEL','VIDEO','DOCS','IMAGES','OTHER'))),
        url varchar(255) not null,
        primary key (id)
    );

    create table task_comment (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_comment_id bigint,
        task_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        user_id bigint not null,
        comment varchar(255),
        primary key (id)
    );

    create table tasks (
        is_recurring boolean not null,
        archived_at timestamp(6) with time zone,
        archived_by bigint,
        completion_date timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        created_by bigint,
        due_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        parent_task_id bigint,
        project_id bigint not null,
        start_date timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        description varchar(255),
        priority varchar(255) check ((priority in ('LOW','MEDIUM','HIGH','URGENT'))),
        status varchar(255) check ((status in ('ASSIGNED','IN_PROGRESS','COMPLETED','OVERDUE','CANCELLED','ARCHIVED','BLOCKED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table user_session (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_used timestamp(6) with time zone,
        login_time timestamp(6) with time zone not null,
        logout_time timestamp(6) with time zone,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        ip_add varchar(255) not null,
        refresh_token varchar(255) not null unique,
        session_status varchar(255) check ((session_status in ('ACTIVE','LOGGED_OUT','EXPIRED','REVOKED'))),
        primary key (id)
    );

    create table user_token (
        is_used boolean not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6) with time zone,
        user_id bigint not null,
        token_hash varchar(255) not null unique,
        token_type varchar(255) not null check ((token_type in ('EMAIL_VERIFICATION','PASSWORD_RESET'))),
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        is_email_verified boolean not null,
        created_at timestamp(6) with time zone not null,
        deactivated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_login_at timestamp(6) with time zone,
        role_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        phone_number varchar(20),
        address varchar(255),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists notification 
       add constraint FKgu7aqnk7lvxtqhhsp8ltpy7il 
       foreign key (project_id) 
       references projects;

    alter table if exists notification 
       add constraint FKplj822fox7js93jahlub1mbap 
       foreign key (sent_by_id) 
       references users;

    alter table if exists notification 
       add constraint FK4j8whmrw0ba72jtrdr1d8guwr 
       foreign key (task_id) 
       references tasks;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKecl5lrd2hnfs258uauscx743w 
       foreign key (invited_by) 
       references users;

    alter table if exists project_invitation 
       add constraint FKlj4qxtgdscr1ubtyp1mt8ty2f 
       foreign key (invited_user_id) 
       references users;

    alter table if exists project_invitation 
       add constraint FKp5cv96sta99mo8au33u1ng0k6 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKdki1sp2homqsdcvqm9yrix31g 
       foreign key (project_id) 
       references projects;

    alter table if exists project_members 
       add constraint FKgul2el0qjk5lsvig3wgajwm77 
       foreign key (user_id) 
       references users;

    alter table if exists projects 
       add constraint FKmueqy6cpcwpfl8gnnag4idjt9 
       foreign key (owner_id) 
       references users;

    alter table if exists recurring_task_rule 
       add constraint FKlm46ahplwu77u52hjqltkq0lo 
       foreign key (task_id) 
       references tasks;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists task_activity 
       add constraint FKs8q6cpgcvag2p3bpsrnna74qx 
       foreign key (project_id) 
       references projects;

    alter table if exists task_activity 
       add constraint FKhgmt5v3fkggo7do977l6cpi0i 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_activity 
       add constraint FK3s0dry6sv8cmc9y0u6kna5wo8 
       foreign key (user_id) 
       references users;

    alter table if exists task_assignment 
       add constraint FKrqc8s1b7r0cxkuvlqhx4vv7rb 
       foreign key (assigned_by) 
       references users;

    alter table if exists task_assignment 
       add constraint FKtcinxxcyh0hdc2md2hh78kvw4 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_assignment 
       add constraint FKakpq2xi7gmbhnk9hpeskx2h0l 
       foreign key (user_id) 
       references users;

    alter table if exists task_attachments 
       add constraint FK4eyiisq4wyx2mfj3p9h8ppufo 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_attachments 
       add constraint FK8g8b4opj0xx4ptu66b8gxkkdo 
       foreign key (uploaded_by) 
       references users;

    alter table if exists task_comment 
       add constraint FK1lcu0hwmljc3yjkqshvgqynpc 
       foreign key (parent_comment_id) 
       references task_comment;

    alter table if exists task_comment 
       add constraint FK7kiv45on4bf6my8w8mhefy9jy 
       foreign key (task_id) 
       references tasks;

    alter table if exists task_comment 
       add constraint FKo2c4nu60419sd7mn9qexf4cqa 
       foreign key (user_id) 
       references users;

    alter table if exists tasks 
       add constraint FKb2q92d8ri0fvbojumew2omd3 
       foreign key (archived_by) 
       references users;

    alter table if exists tasks 
       add constraint FK9dgm9t7wn4w3gh57h63g712lo 
       foreign key (created_by) 
       references users;

    alter table if exists tasks 
       add constraint FK76tiq4q248au3u79a8nkexoth 
       foreign key (parent_task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKsfhn82y57i3k9uxww1s007acc 
       foreign key (project_id) 
       references projects;

    alter table if exists user_session 
       add constraint FKlr29o11uswdgcnn8swu3q15f8 
       foreign key (user_id) 
       references users;

    alter table if exists user_token 
       add constraint FKfadr8tg4d19axmfe9fltvrmqt 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;
